spring:
  redis:
    cluster:
      nodes: 127.0.0.1:6001,127.0.0.1:6002,127.0.0.1:6003,127.0.0.1:6004,127.0.0.1:6005,127.0.0.1:6006
      max-redirects: 3 # 获取失败 最大重定向次数
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: -1

subscribe-queue-size : 3
subscribe-queue-pool-size : 2000
